# Site settings
title: 慧心 | 博客
description: "慧心's blog, build with github."
url: "http://RealFangChunLin.github.io"
author:
  name: "RealFangChunLin"
  email: "getfs1@163.com"
  url: "http://RealFangChunLin.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
